<a href="https://colab.research.google.com/github/UtkKnight10/NumPy/blob/main/Mathematics_using_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import sys

## **Mathematics using NumPy**

#### Arithematic operations

In [ ]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


These a element wise operations.
That means every element will be changed.

In [ ]:
a + 2

array([3, 4, 5, 6])

In [ ]:
a - 2

array([-1,  0,  1,  2])

In [ ]:
a * 2

array([2, 4, 6, 8])

In [ ]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [ ]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [ ]:
a ** 2

array([ 1,  4,  9, 16])

#### Trignometric operation

In [ ]:
# Take the sine
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [ ]:
# Take the cosine
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [ ]:
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128])

#### **Linear algebra**

In linear algebra we are not doing element wise operations

In [ ]:
a = np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
b = np.full((3,2), 2)
print(b)

[[2 2]
 [2 2]
 [2 2]]


Matrix multiplication

In [ ]:
# a * b -> gives an error as we cant multiply matrix like this
# we have to use matmul() to multiply the matrices
# The dimensions of the matrix should be compatible.
# It means that number of columns in 'a' matrix should be equal to number of rows in 'b' matrix
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

Finding Determinant

In [ ]:
c = np.identity(3)
np.linalg.det(c)

1.0

In [ ]:
# Reference doc: https://docs.scipy.org/doc/numpy/reference/routines.linalg.html

# Determinant
# Trace
# Singular vector decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

Statistics

In [ ]:
stats = np.array([[1,2,3], [4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.min(stats)

1

In [ ]:
# axis = 1 gives the row wise minimum
# axis = 0 gives the column wise minimum
np.min(stats, axis=1)

array([1, 4])

In [ ]:
np.max(stats)

6

In [ ]:
# axis = 1 gives the row wise max
# axis = 0 gives the column wise max
np.max(stats, axis=1)

array([3, 6])

In [ ]:
np.sum(stats)

21

In [ ]:
# axis = 1 gives the row wise sum -> gives sum of of all elements in the row
# axis = 0 gives the column wise sum -> gives sum of all elements in the column
np.sum(stats, axis=0)

array([5, 7, 9])

#### **Reorganizing Arrays**

In [ ]:
before = np.array([[1,2,3,4], [5,6,7,8]])
print(before)

# as long as multiplication of dimensions of after array
# is equal to total number of elements in before array it is fine
after = before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# Vertically stacking vectors
# The number of columns in the arrays should be same
v1 = np.array([[1,2,3,4], [1,1,1,1]])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [1, 1, 1, 1],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [1, 1, 1, 1],
       [5, 6, 7, 8]])

In [ ]:
# Horizontal stacking vectors
# The number of rows in the arrays should be same
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

#### **Miscellaneous**

##### Load Data from file

In [ ]:
file_data = np.genfromtxt('data.txt', delimiter=',')
file_data = file_data.astype('int32')
print(file_data)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


##### Boolean Masking and Advanced Indexing

In [ ]:
file_data[file_data > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [ ]:
# We can index with a list in Numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]] # here [1,2,8] this list acts as the index values to be accessed

array([2, 3, 9])

In [ ]:
# Want to know if any value in the columns is greater than 50
# rows put axis = 1
np.any(file_data > 50, axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [ ]:
# want to know if all values in the columns are greater than 50
# for rows put axis = 1
np.all(file_data > 50, axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [ ]:
(~((file_data > 50) & (file_data < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])