<a href="https://colab.research.google.com/github/UtkKnight10/NumPy/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **What is NumPy?**

* Numpy is a multi-dimensional array library
* We can store 1D, 2D, 3D,.... upto N-Dimensional arrays

## **How are Lists diferent from NumPy?**

#####  Lets say we have a (3X4) metrix with all integer values => [[3, 1, 2, 4],[**5**, 7, 1, 2][4, 1, 0, 1]]

* lets take 5 from the metrix and see how it is stored in the numpy array and lists

* **In numpy 5 ==> 00000101(Binary) ==> 00000000 00000000 00000000 00000101(Int32)**

* **In Lists 5==> 00000101 ==> Need lot more information to store this integer**
#### Lists uses built-in int type it consists of 4 things
##### **Size**:- Size of the integer value
##### **Reference Count**:- How many times that integer is being pointed at
##### **Object Type**:-
##### **Object Value**:- it has its own bits assosiated with it

* In Lists **5 ==> 00000000 00000000 00000000 00011100(Size)**
##### **00000001 00111101 11111110 10111100 00011010 11011101 10100100 11011000(Reference Count)**
##### **11001010 10111110 01100001 01000100 11111100 00000000 11001100 01011111(Object Type)**
##### **00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000101(Object Value)**

##### **Benefits of Contiguous Memory**
* SIMD Vector Processing
* Effective Cache Utilization

### **Lists**
* Lists are slower because its takes lot more space than numpy
* Each element has to be type checked while iterating through it
* Lists doesnt ustilize Contiguous memory
##### The list is actually containing pointer to the actual information scattered around the computer memory
* Insertion, deletion, appending, concatination, etc.

### **NumPy**
* NumPy is faster than lists because numpy uses fixed types
* NumPy doesn't requires type checking
* Numpy utilizes Contiguous Memory
##### All the elements of the array are stored next to each other in the computer memory
* Insertion, deletion, appending, concatination, etc. and lots more

### **Application of NumPy?**
* Mathematics (MATLAB Replacement)
* Plotting (Matplolib)
* Backend (Pandas, Connect4, Digital Photography)
* Machine Learning

## **Load in NumPy(remember to pip install numpy first)**

In [ ]:
import numpy as np
import sys

## **The Basics**

#### **Initialize the array**

In [ ]:
a = np.array([1,2,3], dtype='int32') # dtype specify the type of int to be stored
print(a)

[1 2 3]


In [ ]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [ ]:
# Get the dimensions
print("dimensions of a-> ",a.ndim)
print("dimensions of b-> ",b.ndim)

dimensions of a->  1
dimensions of b->  2


In [ ]:
# Get shape
print("Shape of a-> ",a.shape)
print("Shape of b-> ",b.shape)

Shape of a->  (3,)
Shape of b->  (2, 3)


In [ ]:
# Get Type
print("Type of a-> ",a.dtype)
print("Type of b-> ",b.dtype)

Type of a->  int16
Type of b->  float64


In [ ]:
# Get size
print("Size of a->", a.itemsize)
print("Size of b->", b.itemsize)

Size of a-> 4
Size of b-> 8


In [ ]:
# Get total size
total_size = a.size * a.itemsize
print("Total size of a-> ",total_size)
total_size = b.size * b.itemsize
print("Total size of b-> ",total_size)

Total size of a->  12
Total size of b->  48


In [ ]:
# alternate
a.nbytes

12

#### **Accessing/ Changing specific elements, rows, columns, etc.**

In [ ]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
# get a specific element [r, c]
a[1, 5]

13

In [ ]:
# Get specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [ ]:
# Getting a little more fancy [start index: stepsize]
# every other element between 2 and 6
a[0, 1:-1:2]

array([2, 4, 6])

In [ ]:
# Changing the specific element value
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [ ]:
# Chnaing entire column
a[:, 2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [ ]:
# Changing entire row
a[1, :] = 5
print(a)

[[1 2 1 4 5 6 7]
 [5 5 5 5 5 5 5]]


##### 3d example

In [ ]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# Getting specific element (work outside in)
# want the 4 in the array
print(b[0,1,1])
print("-------------------------------------")
# Want a specific range of elements
print(b[:,1,:])

4
-------------------------------------
[[3 4]
 [7 8]]


In [ ]:
# Replace
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


#### **Initialize Different Types of Array**

In [ ]:
# All 0s matrix:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# All 1s matrix:
np.ones((4,2,2), dtype='int32') # dtype specify the data type of the integer

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [ ]:
# Any other number
# np.full takes mainly 2 parameters -> shape and value# Two parameters -> shape and value
# np.full(shape, value)
# can have third parameter-> dtype
# np.full(shape, value, dtype)
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])